onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "esbuild"
  - "prisma"
  - "sharp"
  - "unrs-resolver"
allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  '@sentry/cli': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@apm-js-collab/code-transformer-bundler-plugins@0.6.1'
  - '@sentry/browser-utils@10.66.0'
  - '@sentry/browser@10.66.0'
  - '@sentry/core@10.66.0'
  - '@sentry/feedback@10.66.0'
  - '@sentry/nextjs@10.66.0'
  - '@sentry/node-core@10.66.0'
  - '@sentry/node@10.66.0'
  - '@sentry/opentelemetry@10.66.0'
  - '@sentry/react@10.66.0'
  - '@sentry/replay-canvas@10.66.0'
  - '@sentry/replay@10.66.0'
  - '@sentry/server-utils@10.66.0'
  - '@sentry/vercel-edge@10.66.0'
